version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Changing directory to fridge-app
      - cd ./fridge-app
      - echo Installing dependencies
      - pip install -r requirements.txt
  build:
    commands:
      - pytest tests/