Description: Create a Docker CI/CD pipeline with CodePipeline, CodeBuild and ECR

Parameters:

  AppName:
    Description: Choose the name for the app
    Type: String
    Default: fridge_app

  AWSGitHubConnection:
    Description: GitHub AWS connection created previously as it requires manual authentication process
    Type: String
    Default: aws_github_connection

  GitHubOwner:
    Description: The owner of the GitHub repo
    Type: String
    Default: nikodyulger

  GitHubRepo:
    Description: The GitHub repository name
    Type: String
    Default: aws_fridge_app

  Metadata:
    AWS::CloudFormation::Interface:
      ParameterGroups:
        - Label:
            default: "CodePipeline Settings"
          Parameters:
            - AppName
            - AWSGitHubConnection
        - Label:
            default: "GitHub Settings"
          Parameters:
            - GitHubOwner
            - GitHubRepo

Resources:

  ECR: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref AppName
      ImageScanningConfiguration: 
        ScanOnPush: true

  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AppName}_artifactstore_bucket
      VersioningConfiguration:
        Status: Enabled

  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: ArtifactStoreBucket
    Properties:
      Name: !Sub ${AppName}-cicd-pipeline
      RoleArn: !GetAtt Pipelinerole.Arn
      ArtifactStore:
        Location: !Ref ArtifactStoreBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Sub arn:${AWS::Partition}:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/${AWSGitHubConnection}
                FullRepositoryId: !Sub ${GitHubOwner}/${GitHubRepo}/${AppName}
                BranchName: master
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: Test and Build
          Actions:
            - Name: Test
              ActionTypeId:
                Category: Test
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeTest
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 2
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 3